### ISSUE TITLE
Support for docker data volumes (persisent data) in ONEdock?

### ISSUE THREAD

**Issue by hydro-b** [indigo-dc/onedock#11]
Is it possible (with the current ONEdock release) to provide a container with a (persistent) data volume? Either a "named" volume or a shared directory from the host? I've tried "attaching" a disk in OpenNebula and got "/var/tmp/one/vmm/onedock/attach_disk: No such file or directory". Not even sure if you can attach a volume to a running container.

**Comment by dealfonso** [comment]
Hi @hydro-b

the current release does not support attaching volumes to running containers, but it should be possible to assign a persistent volume from other datastore (e.g. a file datastore such as 'default') to a container at the creation time.

Regards.

**Comment by hydro-b** [comment]
Ok, but a "FILE" datastore is only able to provide "context, ramdisk, or kernel" files, not a disk image.

Disk image defined in template (at creation time) gives error below:

Thu Jan 21 13:31:14 2016 [Z0][VMM][D]: Message received: LOG I 80 Command execution fail: cat << EOT | /var/tmp/one/vmm/onedock/deploy '/var/lib/one//datastores/109/80/deployment.0' 'host06' 80 host06

Thu Jan 21 13:31:14 2016 [Z0][VMM][D]: Message received: LOG I 80 Thu, 21 Jan 2016 13:31:13 +0100 - /var/tmp/one/vmm/onedock/deploy /var/lib/one//datastores/109/80/deployment.0 host06 80 host06

Thu Jan 21 13:31:14 2016 [Z0][VMM][D]: Message received: LOG I 80 Thu, 21 Jan 2016 13:31:14 +0100 - setup_disk /var/lib/one//datastores/109/80 1 vdb /var/lib/one//datastores/109/80/deployment.devices

Thu Jan 21 13:31:14 2016 [Z0][VMM][D]: Message received: LOG I 80 cat: /sys/class/block/nbd*/size: No such file or directory

Thu Jan 21 13:31:14 2016 [Z0][VMM][D]: Message received: LOG I 80 Thu, 21 Jan 2016 13:31:14 +0100 - FAILED: could not setup disk 1 (could not find free devices to connect disk 1)

Thu Jan 21 13:31:14 2016 [Z0][VMM][D]: Message received: LOG E 80 could not setup disk 1 (could not find free devices to connect disk 1)

Thu Jan 21 13:31:14 2016 [Z0][VMM][D]: Message received: LOG E 80 could not setup devices for deployment /var/lib/one//datastores/109/80/deployment.0

Thu Jan 21 13:31:14 2016 [Z0][VMM][D]: Message received: LOG I 80 ExitCode: 255

Thu Jan 21 13:31:14 2016 [Z0][VMM][D]: Message received: LOG I 80 Failed to execute virtualization driver operation: deploy.

**Comment by hydro-b** [comment]
I've made a command similar to "DOCKERRUN", i.e. "DOCKERVOL" which can be used in image defintion to share a (host) filesytem directory (volume). I'll send a pull request.

**Comment by dealfonso** [comment]
Sorry, I made a mistake when refering to the "FILES" type... I meant that you should be able to use a volume from a "IMAGE" datastore. In the _test_ folder you have a file named _009-test-create-vm-5-disk-persistent_ in which the usage of persistent volumes at creation time is demonstrated.

The workflow is
1) creating a persistent image in the "default" datastore (usually with id: 1), which is from type "IMAGE" in the default installation.
2) assign it in a template: 
e.g.

```
cat > /tmp/onedock.vm << EOT
NAME = container-img-1
CPU = 1
MEMORY = 1024
DISK = [ IMAGE=ubuntu ]
DISK = [ IMAGE_ID=1 ]
NIC = [ NETWORK_ID=0 ]
CONTEXT = [ NETWORK = "YES" ]
EOT
```

3) instantiate the template to a VM.

This volume should be available for the container in the target device to which ONE assigns the volume. If you issue a `onevm show ID -x`, the target is stored in the **/VM/TEMPLATE/DISK/TARGET** field from the corresponding volume. You should be able to mount that volume inside the container. Moreover, if the volume is partitioned, the partitions will also be available inside the container (e.g. if the target is **hdc**, the partitions should be available as **/dev/hdc1**, **/dev/hdc2**, etc.). The caveat here is that, in the current version, if you partition the disk inside the container, the container must be terminated before the partitions appear inside a container.

If you test it, please give us feedback about your experience.

Thank you in advance.

**Comment by hydro-b** [comment]
Ok, that was indeed what I had done ... turns out that nbd module is not loaded because CentOS 7 (by default) does not have it :/.

**Comment by dealfonso** [comment]
@hydro-b, we are preparing documentation to describe the proper installation for CentOS. I hope that it will help.

**Comment by hydro-b** [comment]
On Thu, Jan 28, 2016 at 08:09:27AM -0800, Carlos de Alfonso wrote:

> @hydro-b, we are preparing documentation to describe the proper
> installation for CentOS. I hope that it will help.

Thanks.

In the meantime ... I've been setting up ONEdock with Ubuntu Wily
(15.10) hosts. I had to add the following  "--format=raw" to avoid
triggering a qemu-nbd error:

sudo /usr/bin/qemu-nbd -c $NBD_TGT "${FOLDER}/disk.${DISK_ID}"
"--format=raw" 2> /dev/null

(line 28 in vmmfnc.sh).

On what OS do you develop ONEdock?

Regarding the "--format=raw" flag ... I would like to make the
"--format=" a variable which depends on the image type of $DISK_ID. This
code might already be somewhere in core opennebula drivers somewhere.

Gr. Stefan

**Comment by dealfonso** [comment]
Hi,

The --format flag, qemu-nbd is supposed to auto-detect the format of the disk. I'll try to reproduce the error that you found and see what is happening. Anyway the format of the disk is stored in ONE.

About your last question, ONEDock is mainly developed on an Ubuntu 14.04 LTS server.

Regards.
