### ISSUE TITLE
VNC access to the docker vm

### ISSUE THREAD

**Issue by solstarz** [indigo-dc/onedock#14]
Hi,

What is the status of solving the vnc issue?

**Comment by dealfonso** [comment]
hi, we are working on it... I hope that we will have one version in few days

**Comment by solstarz** [comment]
Hi, thanks for the info

**Comment by dealfonso** [comment]
Hi @solstarz 

I have just created one new [branch which is called VNC](https://github.com/indigo-dc/onedock/tree/vnc) that provides VNC support for the containers. The VNC console integrates with sunstone.

You need to install [svncterm](https://github.com/dealfonso/svncterm) in every virtualization node, and give sudo permissions for the application /usr/bin/svncterm in file /etc/sudoers.d/opennebula

Could you please try it?
- [svncterm](https://github.com/dealfonso/svncterm) is a version that simplifies [vncterm from proxmox](https://github.com/proxmox/vncterm), to avoid the TLS communication that is not needed for ONEDock, to enable passwordless VNC consoles, and to avoid the need of patching the libvncserver library.

**Comment by solstarz** [comment]
Hi,

Thanks for the update.

I followed your steps to install the svncterm, but in the docker container it fails. Or im messing up.
Maybe you can guide me in the right direction.

Thanks in advance

**Comment by dealfonso** [comment]
Hi @solstarz 
could you please provide some more information about the errors? e.g. the /var/log/one/<VMID>.log file and/or the /var/log/onedock.log file.

**Comment by solstarz** [comment]
Hi @dealfonso 

The log files shows no errors or entry of the svncterm installation.
I did following:

One the Onehost:
- Compile this app
  apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y make build-essential zlib1g-dev console-data quilt libgnutls-dev libjpeg-dev libvncserver-dev
  git clone https://github.com/dealfonso/svncterm
  cd svncterm/
  make
- Make the redistributable .deb file by using this command:
  $ make deb

Then copied the newly made .deb file to a docker container.

Could be my steps are wrong.

**Comment by dealfonso** [comment]
Hi @solstarz 

You must install svncterm in the virtualization hosts, not in the docker container. I tried to explain in [section 3.2](https://github.com/indigo-dc/onedock/tree/vnc#32-computing-nodes) in the readme of this PR. Moreover you need to adjust the /etc/sudoers.d/opennebula to enable oneadmin to _sudo_ vncterm. Could you please try it?

**Comment by solstarz** [comment]
Hi @dealfonso,

Followed your steps im moving foward. But im now getting the connection refused.

Error message:
[07/Mar/2016 23:16:05] connecting to: opennebula:5923
handler exception: [Errno 111] Connection refused

But i think this not an issue of the svnc.

**Comment by dealfonso** [comment]
Hi @solstarz 

I don't know why you are having that problem, but I think that maybe you can check whether you are using "localhost" somewhere as the address in which the vnc server is listening.

**Comment by dealfonso** [comment]
Hi @solstarz,

I found one bug in VNC, and I have corrected. Can you try the master branch? (VNC branch has been merged because it has been verified).

**Comment by dealfonso** [comment]
VNC support is now included in the master branch
