### ISSUE TITLE
Include xmlstarlet package requirement in the documentation

### ISSUE THREAD

**Issue by alvarosimon** [indigo-dc/onedock#7]
Hi

I found that to set correctly the VM container network in docker you must install `xmlstarlet` package (at least from a CentOS7 machine), from the logs:

> Fri Dec  4 11:27:14 2015 [Z0][VMM][D]: Message received: LOG I 0 /var/tmp/one/vmm/onedock/deploy: line 68: xmlstarlet: command not found

and the network interface is not available from the container, but after the package installation everything works as expected!
Please include in the **Environmet** section that onedock requires `xmlstarlet` to work.

Thanks a lot!

**Comment by dealfonso** [comment]
Hi @alvarosimon,

thank you. You are right, I am preparing documentation for centos, because some packages are needed (e.g. jq, xmlstarlet and bridge-utils).

Regards
